version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/Moscow
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: org.projectlombok:lombok
    versions:
    - 1.18.18
